### ISSUE TITLE
Software (Backend): Setup shared variables for interaction between process streaming data in and process running application

### ISSUE THREAD

**Issue by mlej8** [NTX-McGill/NeuroTechX-McGill-2021#76]
There will be two processes:
1. Process that is running `stream.py` to stream the data in from the OpenBCI device
2. Process running the flask application

We need to use a way to interact between these two processes. We can use shared variables to communicate between the flask app and the process streaming data. When the user clicks on a key of the keyboard, it will send a POST request to the backend of the flask app that contains the key the user pressed. The backend needs to communicate to `stream.py` which key the user has pressed and label all upcoming data with this character as their label. Please post a comment under this issue if this needs more explanation.

**Comment by TheFloatingString** [comment]
Update as of December 29, 2021:

* Created minimal endpoints for `collection/start` and `collection/stop`
* Added commented placeholder code in `collection/stop` for adding queue items to database

**Comment by TheFloatingString** [comment]
Update as of December 29, 2021:

* Created minimal endpoints for collection/start and collection/stop
* Added commented placeholder code in collection/stop for adding queue items to database
* Will create a tentative PR for code review later today

**Comment by mlej8** [comment]
Update as of February 5th, we are going back to use single shared variables due to `Manager()` objects not running on MacOS. @TheFloatingString will be in charge for this task.

**Comment by mlej8** [comment]
Solved by using singleton pattern.
