### ISSUE TITLE
Software (Backend): Route to stop collecting for a given character.

### ISSUE THREAD

**Issue by mlej8** [NTX-McGill/NeuroTechX-McGill-2021#89]
@TheFloatingString already started it in his branch for this task, checkout to his branch and rebase main

This route is called by the front end when it highlights a character for the second time.

Create a POST route that receives the following information: (process_id: int)
1. set the shared variable "collecting" to False in order to stop collecting in the BCI process.
2.  flush everything inside of `bci_processes_states[process_id]["queue"]` to the database. See `NeuroTechX-McGill-2021/software/data_collection_platform/backend/dcp/tasks.py` for reference on how to write to the database.

Tagging @HassanKanj16 @TheMatrixMaster to keep frontend in the loop on progress for backend routes

**Comment by wykzhang** [comment]
Any reason why this route is a post?

**Comment by mlej8** [comment]
Reasoning behind this is `GET` requests shouldn't modify the state of the backend. However, this route does modify the state of the backend, hence we can either go with `POST` or `PUT`. 

![image](https://user-images.githubusercontent.com/43357040/149431270-60e1d5ad-4267-4bef-8748-262caeee58cb.png)

Regarding `POST` vs `PUT`, I think `PUT` might be better suited as we are modifying the state of something in the backend here.

**Comment by wykzhang** [comment]
Just making sure, we don't need to retain the order of the BCI data? (I saw that we were keeping track of order last year)
