### ISSUE TITLE
Software (Backend): Make a script to clear all rows for all tables using flask SQLAlchemy

### ISSUE THREAD

**Issue by mlej8** [NTX-McGill/NeuroTechX-McGill-2021#99]
Sometimes we need to clear the local dev database, hence it would be good to have a script that erases all entries in all tables using `flask-SQLAlchemy`.

**Comment by mlej8** [comment]
Please update the status on this task @gupta-parth

**Comment by gupta-parth** [comment]
I was thinking of creating a bash script to clear the database, but I'll look into it using SQLAlchemy.
